'use client'

import { GraduationCap, Backpack, Loader2 } from 'lucide-react'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { AuthShell, Message, inputClass } from '@/components/auth/AuthShell'
import { useAuth } from '@/hooks/useAuth'

export default function SelectRolePage() {
  const { user } = useAuth(); const router = useRouter(); const [role, setRole] = useState<'teacher' | 'student' | ''>(''); const [school, setSchool] = useState(''); const [grade, setGrade] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const save = async () => { if (!role) return setError('Choose a role to continue.'); if (role === 'teacher' && !school.trim()) return setError('Please enter your school name.'); if (role === 'student' && !grade) return setError('Please choose your grade.'); setLoading(true); const { error: authError } = await (await import('@/lib/supabaseClient')).supabase.auth.updateUser({ data: { role, school_name: school.trim() || null, grade_level: grade ? Number(grade) : null } }); setLoading(false); if (authError) setError(authError.message); else router.replace(role === 'teacher' ? '/teacher/dashboard' : '/student/dashboard') }
  if (!user) return <AuthShell title="Choose your learning space" subtitle="Sign in is required before choosing a role."><a href="/login" className="block rounded-xl bg-primary py-3 text-center font-semibold text-primary-foreground">Go to Login</a></AuthShell>
  return <AuthShell title="Choose your learning space" subtitle="Tell us how you will use MozhiLearn."><div className="space-y-5">{error && <Message error>{error}</Message>}<div className="grid gap-3 sm:grid-cols-2"><button onClick={() => setRole('teacher')} className={`rounded-2xl border-2 p-5 text-left ${role === 'teacher' ? 'border-primary bg-primary/5' : 'border-border'}`}><GraduationCap className="size-7 text-primary" /><strong className="mt-3 block">Teacher</strong><span className="text-sm text-muted-foreground">Create and guide lessons.</span></button><button onClick={() => setRole('student')} className={`rounded-2xl border-2 p-5 text-left ${role === 'student' ? 'border-primary bg-primary/5' : 'border-border'}`}><Backpack className="size-7 text-primary" /><strong className="mt-3 block">Student</strong><span className="text-sm text-muted-foreground">Learn and take quizzes.</span></button></div>{role === 'teacher' && <label className="block text-sm font-semibold">School Name<input className={inputClass} value={school} onChange={(e) => setSchool(e.target.value)} /></label>}{role === 'student' && <label className="block text-sm font-semibold">Grade Level<select className={inputClass} value={grade} onChange={(e) => setGrade(e.target.value)}><option value="">Choose grade</option>{[1, 2, 3, 4, 5].map((value) => <option key={value} value={value}>Grade {value}</option>)}</select></label>}<button disabled={loading} onClick={save} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground disabled:opacity-60">{loading ? <Loader2 className="size-5 animate-spin" /> : 'Continue'}</button></div></AuthShell>
}
